name: Scrape

on:
  schedule:
    - cron: "*/3 * * * *"   # every 3 minutes
  workflow_dispatch:        # allow manual run too

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm install
        
      - name: Run scraper
        run: node scraper.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}



